FROM python:3.10.12

# Install ffmpeg as a package
RUN apt-get update && apt-get install -y ffmpeg

WORKDIR /app
RUN mkdir -p /log
RUN mkdir -p /images
RUN mkdir -p /audio

RUN pip install RootsWeatherProject==1.0.11

ENV RWP_LOG_DIR=/log
ENV RWP_LOG_LEVEL=DEBUG
ENV MANAGERAPI_BASE_URL="http://localhost:8000/"
ENV IMAGE_DIR=/images
ENV RWP_AUDIOFILE="./audio.mp3"

CMD ["videoMaker"]